/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,ts,tsx,mdx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['"DM Sans"', 'sans-serif'],
        serif: ['"Lora"', 'serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      colors: {
        ink: {
          50:  '#f7f7f5',
          100: '#eeeee9',
          200: '#d5d5cc',
          300: '#b0b0a4',
          400: '#87877a',
          500: '#6a6a5e',
          600: '#55554b',
          700: '#45453d',
          800: '#2e2e28',
          900: '#1a1a16',
          950: '#0d0d0a',
        },
        accent: '#e85d3c',
      },
      typography: (theme) => ({
        DEFAULT: {
          css: {
            '--tw-prose-body': theme('colors.ink[700]'),
            '--tw-prose-headings': theme('colors.ink[900]'),
            '--tw-prose-lead': theme('colors.ink[600]'),
            '--tw-prose-links': theme('colors.accent'),
            '--tw-prose-bold': theme('colors.ink[900]'),
            '--tw-prose-counters': theme('colors.ink[400]'),
            '--tw-prose-bullets': theme('colors.ink[300]'),
            '--tw-prose-hr': theme('colors.ink[100]'),
            '--tw-prose-quotes': theme('colors.ink[900]'),
            '--tw-prose-quote-borders': theme('colors.accent'),
            '--tw-prose-captions': theme('colors.ink[400]'),
            '--tw-prose-code': theme('colors.ink[900]'),
            '--tw-prose-pre-code': theme('colors.ink[100]'),
            '--tw-prose-pre-bg': theme('colors.ink[900]'),
            '--tw-prose-th-borders': theme('colors.ink[200]'),
            '--tw-prose-td-borders': theme('colors.ink[100]'),
            '--tw-prose-invert-body': theme('colors.ink[300]'),
            '--tw-prose-invert-headings': theme('colors.ink[50]'),
            '--tw-prose-invert-lead': theme('colors.ink[400]'),
            '--tw-prose-invert-links': theme('colors.accent'),
            '--tw-prose-invert-bold': theme('colors.ink[50]'),
            '--tw-prose-invert-counters': theme('colors.ink[400]'),
            '--tw-prose-invert-bullets': theme('colors.ink[600]'),
            '--tw-prose-invert-hr': theme('colors.ink[700]'),
            '--tw-prose-invert-quotes': theme('colors.ink[100]'),
            '--tw-prose-invert-quote-borders': theme('colors.accent'),
            '--tw-prose-invert-captions': theme('colors.ink[500]'),
            '--tw-prose-invert-code': theme('colors.ink[50]'),
            '--tw-prose-invert-pre-code': theme('colors.ink[300]'),
            '--tw-prose-invert-pre-bg': 'rgb(0 0 0 / 50%)',
            '--tw-prose-invert-th-borders': theme('colors.ink[600]'),
            '--tw-prose-invert-td-borders': theme('colors.ink[700]'),
            maxWidth: 'none',
            a: { textDecoration: 'none', '&:hover': { textDecoration: 'underline' } },
            'h1,h2,h3': { fontFamily: theme('fontFamily.serif').join(', ') },
            code: { fontSize: '0.875em' },
            pre: { borderRadius: '0.5rem' },
          },
        },
      }),
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
};
